### ISSUE TITLE
Importer fails, apparently because of changes in latest version of SWADE

### ISSUE THREAD

**Issue by flyingsquad** [arnonram/swade-npc-importer#145]
It looks like recent changes to SWADE have broken the importer. I get the error below when I try to import.

I debugged it through the parsing phase and it seems to be reading the data correctly (it dumps a reasonable looking .json object to the console), but fails when it tries to make the character.

foundry.js:655 DataModelValidationError: SwadeActor validation errors:
  items: 
    null: 
      name: may not be undefined
    null: 
      name: may not be undefined
    null: 
      name: may not be undefined
    null: 
      name: may not be undefined
    null: 
      name: may not be undefined
    null: 
      name: may not be undefined
[Detected 2 packages: system:swade(4.2.0), swade-npc-importer(0.2.4)]
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at SwadeActor.validate (foundry-esm.js:10432:61)
    at new DataModel (foundry-esm.js:10181:12)
    at new BaseActor (foundry-esm.js:13233:7)
    at new ClientDocumentMixin (foundry.js:10594:7)
    at new Actor (foundry.js:15521:1)
    at new SwadeActor (SwadeActor.ts:118:5)
    at #preCreateDocumentArray (foundry-esm.js:56385:17)
    at ClientDatabaseBackend._createDocuments (foundry-esm.js:56347:58)
    at ClientDatabaseBackend.create (foundry-esm.js:12281:19)
    at async Actor.createDocuments (foundry-esm.js:11423:23)
    at async Import (foundryActions.js:148:20)
    at async Dialog.callback (actorImporter.js:37:11)

**Comment by arnonram** [comment]
i think this is resolved with the latest release
if still issues, please re-open
